---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.19.0
  name: variantautoscalings.llmd.ai
spec:
  group: llmd.ai
  names:
    kind: VariantAutoscaling
    listKind: VariantAutoscalingList
    plural: variantautoscalings
    shortNames:
    - va
    singular: variantautoscaling
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .spec.modelID
      name: Model
      type: string
    - jsonPath: .spec.variantID
      name: VariantID
      type: string
    - jsonPath: .spec.accelerator
      name: Accelerator
      type: string
    - jsonPath: .status.currentAlloc.numReplicas
      name: CurrentReplicas
      type: integer
    - jsonPath: .status.desiredOptimizedAlloc.numReplicas
      name: Optimized
      type: integer
    - jsonPath: .status.conditions[?(@.type=='MetricsAvailable')].status
      name: MetricsReady
      type: string
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            properties:
              accelerator:
                minLength: 1
                type: string
              acceleratorCount:
                minimum: 1
                type: integer
              maxReplicas:
                format: int32
                minimum: 1
                type: integer
              minReplicas:
                default: 0
                format: int32
                minimum: 0
                type: integer
              modelID:
                minLength: 1
                type: string
              scaleTargetRef:
                properties:
                  apiVersion:
                    minLength: 1
                    type: string
                  kind:
                    minLength: 1
                    type: string
                  name:
                    minLength: 1
                    type: string
                required:
                - kind
                - name
                type: object
              sloClassRef:
                properties:
                  key:
                    minLength: 1
                    type: string
                  name:
                    minLength: 1
                    type: string
                required:
                - key
                - name
                type: object
              variantCost:
                default: "10"
                pattern: ^\d+(\.\d+)?$
                type: string
              variantID:
                minLength: 1
                pattern: ^.+-[A-Za-z0-9_-]+-[1-9][0-9]*$
                type: string
              variantProfile:
                properties:
                  maxBatchSize:
                    minimum: 1
                    type: integer
                  perfParms:
                    properties:
                      decodeParms:
                        additionalProperties:
                          type: string
                        minProperties: 1
                        type: object
                      prefillParms:
                        additionalProperties:
                          type: string
                        minProperties: 1
                        type: object
                    required:
                    - decodeParms
                    - prefillParms
                    type: object
                required:
                - maxBatchSize
                - perfParms
                type: object
            required:
            - accelerator
            - acceleratorCount
            - modelID
            - scaleTargetRef
            - sloClassRef
            - variantID
            - variantProfile
            type: object
            x-kubernetes-validations:
            - message: maxReplicas must be greater than or equal to minReplicas
              rule: '!has(self.maxReplicas) || !has(self.minReplicas) || self.maxReplicas
                >= self.minReplicas'
          status:
            properties:
              actuation:
                properties:
                  applied:
                    type: boolean
                required:
                - applied
                type: object
              conditions:
                items:
                  properties:
                    lastTransitionTime:
                      format: date-time
                      type: string
                    message:
                      maxLength: 32768
                      type: string
                    observedGeneration:
                      format: int64
                      minimum: 0
                      type: integer
                    reason:
                      maxLength: 1024
                      minLength: 1
                      pattern: ^[A-Za-z]([A-Za-z0-9_,:]*[A-Za-z0-9_])?$
                      type: string
                    status:
                      enum:
                      - "True"
                      - "False"
                      - Unknown
                      type: string
                    type:
                      maxLength: 316
                      pattern: ^([a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*/)?(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])$
                      type: string
                  required:
                  - lastTransitionTime
                  - message
                  - reason
                  - status
                  - type
                  type: object
                type: array
                x-kubernetes-list-map-keys:
                - type
                x-kubernetes-list-type: map
              currentAlloc:
                properties:
                  numReplicas:
                    format: int32
                    minimum: 0
                    type: integer
                required:
                - numReplicas
                type: object
              desiredOptimizedAlloc:
                properties:
                  lastRunTime:
                    format: date-time
                    type: string
                  lastUpdate:
                    properties:
                      numReplicasChanged:
                        format: int32
                        maximum: 10000
                        minimum: -10000
                        type: integer
                      reason:
                        type: string
                      updateTime:
                        format: date-time
                        type: string
                    type: object
                  numReplicas:
                    format: int32
                    minimum: 0
                    type: integer
                required:
                - numReplicas
                type: object
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
